import { calcMentorScore, type MentorProfile } from "./types";

function withScore(
  base: Omit<MentorProfile, "score">,
): MentorProfile {
  return { ...base, score: calcMentorScore(base) };
}

export const MOCK_MENTORS: MentorProfile[] = [
  withScore({
    userId: "mentor-001",
    nickname: "닉네임A",
    isVerified: true,
    wasGroupLeader: false,
    averageRating: 4.8,
    reviewCount: 12,
    resolvedDays: 18,
    industry: "카페·음식점",
    region: "서울",
    damageTypes: ["임금체불", "주휴수당"],
    consultingFee: 10000,
    badges: ["인증멘토", "빠른해결"],
    bio: "진정서 핵심은 날짜와 금액이에요. 18일 만에 해결했습니다.",
  }),
  withScore({
    userId: "mentor-002",
    nickname: "닉네임B",
    isVerified: false,
    wasGroupLeader: false,
    averageRating: 5.0,
    reviewCount: 3,
    resolvedDays: 21,
    industry: "편의점",
    region: "경기",
    damageTypes: ["임금체불", "연장수당"],
    consultingFee: 10000,
    badges: [],
    bio: "혼자서 진정서 작성하고 출석조사 다녀와서 21일 만에 받았어요.",
  }),
  withScore({
    userId: "mentor-003",
    nickname: "닉네임C",
    isVerified: true,
    wasGroupLeader: false,
    averageRating: 4.5,
    reviewCount: 7,
    resolvedDays: 30,
    industry: "카페·음식점",
    region: "서울",
    damageTypes: ["임금체불"],
    consultingFee: 10000,
    badges: ["인증멘토", "빠른해결"],
    bio: "처음엔 무서웠지만 생각보다 어렵지 않아요.",
  }),
  withScore({
    userId: "mentor-004",
    nickname: "배달라이더3년차",
    isVerified: true,
    wasGroupLeader: false,
    averageRating: 4.7,
    reviewCount: 9,
    resolvedDays: 25,
    industry: "배달",
    region: "서울",
    damageTypes: ["야간수당", "임금체불"],
    consultingFee: 10000,
    badges: ["인증멘토"],
    bio: "야간수당 떼먹는 사장 노동청 진정해서 합의로 마무리.",
  }),
  withScore({
    userId: "mentor-005",
    nickname: "PC방알바3년",
    isVerified: true,
    wasGroupLeader: false,
    averageRating: 4.6,
    reviewCount: 14,
    resolvedDays: 22,
    industry: "PC방",
    region: "서울",
    damageTypes: ["주휴수당", "야간수당"],
    consultingFee: 10000,
    badges: ["인증멘토", "빠른해결"],
    bio: "주 15시간 안 넘기려는 사장 vs 실제 근무 25시간. 통장 내역으로 입증했어요.",
  }),
  withScore({
    userId: "mentor-006",
    nickname: "학원강사출신",
    isVerified: false,
    wasGroupLeader: false,
    averageRating: 4.3,
    reviewCount: 5,
    resolvedDays: 35,
    industry: "학원",
    region: "경기",
    damageTypes: ["퇴직금", "임금체불"],
    consultingFee: 12000,
    badges: [],
    bio: "1년 이상 근무자 퇴직금 미지급 케이스. 대지급금 청구까지 도와드려요.",
  }),
  withScore({
    userId: "mentor-007",
    nickname: "프랜차이즈매니저",
    isVerified: true,
    wasGroupLeader: false,
    averageRating: 4.9,
    reviewCount: 18,
    resolvedDays: 15,
    industry: "카페·음식점",
    region: "서울",
    damageTypes: ["임금체불", "주휴수당", "연장수당"],
    consultingFee: 15000,
    badges: ["인증멘토", "빠른해결"],
    bio: "프랜차이즈 카페 점장 출신. 매장 한 군데서 동료 3명과 함께 진정 넣어 2주 만에 해결한 경험.",
  }),
  withScore({
    userId: "mentor-008",
    nickname: "편의점야간조",
    isVerified: false,
    wasGroupLeader: false,
    averageRating: 4.4,
    reviewCount: 6,
    resolvedDays: 28,
    industry: "편의점",
    region: "부산",
    damageTypes: ["야간수당", "임금체불"],
    consultingFee: 10000,
    badges: [],
    bio: "야간(22-06시) 가산수당 50% 안 받고 일하는 분들 많아요. 통장 입금액으로 역산하면 답 나옵니다.",
  }),
  withScore({
    userId: "mentor-009",
    nickname: "배달큐레이터",
    isVerified: true,
    wasGroupLeader: false,
    averageRating: 4.8,
    reviewCount: 11,
    resolvedDays: 20,
    industry: "배달",
    region: "경기",
    damageTypes: ["연장수당", "임금체불"],
    consultingFee: 12000,
    badges: ["인증멘토"],
    bio: "쿠팡이츠/배민 라이더 출신. 픽업·배송 시간 캡쳐가 가장 강력한 증거.",
  }),
];
