import type { AttendanceRecord, AttendanceStats } from "./types";

export const MOCK_RECENT_ATTENDANCES: AttendanceRecord[] = [
  {
    id: "att-1",
    workplaceId: "wp-1",
    workplaceName: "xx카페 강남점",
    date: "2026-04-08",
    scheduledStart: "09:00",
    scheduledEnd: "18:00",
    actualCheckIn: "09:05",
    actualCheckOut: "18:02",
    extendedMinutes: 0,
    workedMinutes: 480,
    overtimeMinutes: 0,
    nightWorkedMinutes: 0,
    estimatedWage: 80000,
    status: "checked-out",
  },
  {
    id: "att-2",
    workplaceId: "wp-1",
    workplaceName: "xx카페 강남점",
    date: "2026-04-07",
    scheduledStart: "09:00",
    scheduledEnd: "18:00",
    actualCheckIn: "09:00",
    actualCheckOut: "18:00",
    extendedMinutes: 0,
    workedMinutes: 480,
    overtimeMinutes: 0,
    nightWorkedMinutes: 0,
    estimatedWage: 80000,
    status: "checked-out",
  },
  {
    id: "att-3",
    workplaceId: "wp-1",
    workplaceName: "xx카페 강남점",
    date: "2026-04-05",
    scheduledStart: "10:15",
    scheduledEnd: "17:45",
    actualCheckIn: "10:15",
    actualCheckOut: "17:45",
    extendedMinutes: 0,
    workedMinutes: 390,
    overtimeMinutes: 0,
    nightWorkedMinutes: 0,
    estimatedWage: 65000,
    status: "checked-out",
  },
  {
    id: "att-4",
    workplaceId: "wp-1",
    workplaceName: "xx카페 강남점",
    date: "2026-04-04",
    scheduledStart: "09:00",
    scheduledEnd: "18:00",
    actualCheckIn: "09:10",
    actualCheckOut: "18:05",
    extendedMinutes: 0,
    workedMinutes: 475,
    overtimeMinutes: 0,
    nightWorkedMinutes: 0,
    estimatedWage: 80000,
    status: "checked-out",
  },
];

export const MOCK_STATS: AttendanceStats = {
  weeklyWorkedHours: 32.5,
  weeklyWage: 325000,
  weeklyWorkDays: 4,
  weeklyTargetHours: 40,
};

/** 현재 진행 중인 근무 세션 (있으면 표시, 없으면 null). */
export const MOCK_ACTIVE_SESSION: AttendanceRecord | null = {
  id: "att-current",
  workplaceId: "wp-1",
  workplaceName: "xx카페 강남점",
  date: "2026-04-09",
  scheduledStart: "09:00",
  scheduledEnd: "18:00",
  actualCheckIn: "09:03",
  extendedMinutes: 0,
  workedMinutes: 327, // 5시간 27분
  overtimeMinutes: 0,
  nightWorkedMinutes: 0,
  estimatedWage: 0,
  status: "working",
};
